In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn.decomposition

In [3]:
contribution_colnames = [
    'identification_id',
    'amendment_indicator',
    'report_type',
    'primary-general_indicator',
    'image_number',
    'transaction_type',
    'entity_type',
    'contributor_name',
    'city',
    'state',
    'zip_code',
    'employer',
    'occupation',
    'transaction_date',
    'transaction_amount',
    'other_id',
    'candidate_id',
    'transaction_id',
    'file_id',
    'memo_code',
    'memo_text',
    'fec_record_number'
]

In [19]:
input_df = pd.read_csv('/Users/nimish/Code/PoliticalClustering/itpas2.txt', 
                 sep='|',
                 header=None,
                 names=contribution_colnames
                )

/Users/nimish/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (10,11,12,19,20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [41]:
g2016 = input_df[input_df['primary-general_indicator'] == 'G2016']

In [54]:
df = g2016.groupby(
    ['candidate_id', 'contributor_name']
)['transaction_amount'].sum().abs().reset_index()

In [55]:
pivot_matrix = df.pivot_table(
    values='transaction_amount', 
    index='candidate_id', 
    columns='contributor_name'
)

In [88]:
pivot_matrix.head()

contributor_name   HENSARLING, JEB   HOEVEN FOR SENATE  \
candidate_id                                             
H0AL02087                      NaN                 NaN   
H0AL05163                      NaN                 NaN   
H0AL07086                      NaN                 NaN   
H0AR01083                      NaN                 NaN   
H0AR03055                      NaN                 NaN   

contributor_name   NANCY PELOSI FOR CONGRESS  00KING FOR CONGRESS  \
candidate_id                                                        
H0AL02087                                NaN                  NaN   
H0AL05163                                NaN                  NaN   
H0AL07086                                NaN                  NaN   
H0AR01083                                NaN                  NaN   
H0AR03055                                NaN                  NaN   

contributor_name  0WHITEHOUSE FOR SENATE  100% DE AGAVE  \
candidate_id                                              
H0AL02087                            NaN            NaN   
H0AL05163                            NaN            NaN   
H0AL07086                            NaN            NaN   
H0AR01083                            NaN            NaN   
H0AR03055                            NaN            NaN   

contributor_name  1199 SERVICE EMPLOYEES INT'L UNION FEDERAL POLITICAL ACTION FUND  \
candidate_id                                                                         
H0AL02087                                                       NaN                  
H0AL05163                                                       NaN                  
H0AL07086                                                       NaN                  
H0AR01083                                                       NaN                  
H0AR03055                                                       NaN                  

contributor_name  18TH STREET PROJECTS, LLC  2015 SENATORS CLASSIC COMMITTEE  \
candidate_id                                                                   
H0AL02087                               NaN                              NaN   
H0AL05163                               NaN                              NaN   
H0AL07086                               NaN                              NaN   
H0AR01083                               NaN                              NaN   
H0AR03055                               NaN                              NaN   

contributor_name  2016 SENATORS CLASSIC COMMITTEE  ...  ZINKE, RYAN  \
candidate_id                                       ...                
H0AL02087                                     NaN  ...          NaN   
H0AL05163                                     NaN  ...          NaN   
H0AL07086                                     NaN  ...          NaN   
H0AR01083                                     NaN  ...          NaN   
H0AR03055                                     NaN  ...          NaN   

contributor_name  ZINKE, RYAN K  ZIP MAILING SERVICES INC.  \
candidate_id                                                 
H0AL02087                   NaN                        NaN   
H0AL05163                   NaN                        NaN   
H0AL07086                   NaN                        NaN   
H0AR01083                   NaN                        NaN   
H0AR03055                   NaN                        NaN   

contributor_name  ZIP MAILING SERVICES, INC.  ZIPCAR  ZOKAITES, JENNIFER  \
candidate_id                                                               
H0AL02087                                NaN     NaN                 NaN   
H0AL05163                                NaN     NaN                 NaN   
H0AL07086                                NaN     NaN                 NaN   
H0AR01083                                NaN     NaN                 NaN   
H0AR03055                                NaN     NaN                 NaN   

contributor_name  ZONE, CARSON JAMES  ZULETA, IVAN  ZUNIGA, EMILI

In [56]:
nmf = sklearn.decomposition.NMF(n_components=10)

In [90]:
tst

array([[1.65738824e-06, 2.09703193e-06, 6.29030452e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.03856071e-06, 3.84444334e-06, 1.15315355e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.05721112e-11, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.04160627e+02, ...,
        5.20337455e+02, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.78581198e-04, ...,
        4.35518753e-03, 0.00000000e+00, 0.00000000e+00]])

In [60]:
tst = nmf.fit_transform(pivot_matrix.fillna(0))

In [71]:
import scipy.spatial as sp

In [70]:
cand_id_index = pivot_matrix.index

In [76]:
kd = sp.kdtree.KDTree(tst)

In [83]:
kd.query(tst[100], k=10)

(array([0.        , 0.00157477, 0.00157721, 0.00162986, 0.00165612,
        0.00209912, 0.00220618, 0.00240855, 0.00241691, 0.00254863]),
 array([100, 287, 585, 110, 950, 761, 155, 531, 217,  33]))

In [87]:
candidates[candidates['CAND_ID'].isin([cand_id_index[100], cand_id_index[531]])]

CAND_ID          CAND_NAME CAND_ICI  PTY_CD CAND_PTY_AFFILIATION  \
299   H6CA39020      ROYCE, ED MR.        I       2                  REP   
1632  H0OH16097  RENACCI, JAMES B.        I       2                  REP   

      TTL_RECEIPTS  TRANS_FROM_AUTH    TTL_DISB  TRANS_TO_AUTH     COH_BOP  \
299     4456337.02        196744.32  3663387.68            0.0  2014545.98   
1632    2107393.77         19339.17  1768258.71            0.0   285410.26   

      ...  SPEC_ELECTION  PRIM_ELECTION  RUN_ELECTION  GEN_ELECTION  \
299   ...            NaN            NaN           NaN           NaN   
1632  ...            NaN            NaN           NaN           NaN   

      GEN_ELECTION_PRECENT  OTHER_POL_CMTE_CONTRIB  POL_PTY_CONTRIB  \
299                    NaN              1297894.50           3507.5   
1632                   NaN              1399418.29              0.0   

      CVG_END_DT INDIV_REFUNDS  CMTE_REFUNDS  
299   12/31/2016       13800.0          0.00  
1632  12/31/2016        5750.0       6959.84  

[2 rows x 30 columns]

In [50]:
overall_colnames = [
    'CAND_ID', 'CAND_NAME', 'CAND_ICI', 'PTY_CD',
       'CAND_PTY_AFFILIATION', 'TTL_RECEIPTS', 'TRANS_FROM_AUTH',
       'TTL_DISB', 'TRANS_TO_AUTH', 'COH_BOP', 'COH_COP', 'CAND_CONTRIB',
       'CAND_LOANS', 'OTHER_LOANS', 'CAND_LOAN_REPAY', 'OTHER_LOAN_REPAY',
       'DEBTS_OWED_BY', 'TTL_INDIV_CONTRIB', 'CAND_OFFICE_ST',
       'CAND_OFFICE_DISTRICT', 'SPEC_ELECTION', 'PRIM_ELECTION',
       'RUN_ELECTION', 'GEN_ELECTION', 'GEN_ELECTION_PRECENT',
       'OTHER_POL_CMTE_CONTRIB', 'POL_PTY_CONTRIB', 'CVG_END_DT',
       'INDIV_REFUNDS', 'CMTE_REFUNDS'
]

In [51]:
candidates = pd.read_csv('/Users/nimish/Code/PoliticalClustering/weball16.txt', 
                 sep='|', 
                 header=None,
                 names=overall_colnames
                )

In [52]:
candidates[candidates['CAND_ID']=='S6NV00028']

CAND_ID    CAND_NAME CAND_ICI  PTY_CD CAND_PTY_AFFILIATION  \
2760  S6NV00028  REID, HARRY        I       1                  DEM   

      TTL_RECEIPTS  TRANS_FROM_AUTH   TTL_DISB  TRANS_TO_AUTH    COH_BOP  ...  \
2760      258868.0          11295.0  1343367.0            0.0  1457274.0  ...   

      SPEC_ELECTION  PRIM_ELECTION  RUN_ELECTION  GEN_ELECTION  \
2760            NaN            NaN           NaN           NaN   

      GEN_ELECTION_PRECENT  OTHER_POL_CMTE_CONTRIB  POL_PTY_CONTRIB  \
2760                   NaN                145500.0              0.0   

      CVG_END_DT INDIV_REFUNDS  CMTE_REFUNDS  
2760  12/31/2016      450478.0      310035.0  

[1 rows x 30 columns]